spring:

  application:
    name: consumer

  # MongoDB Connection Configuration
  # This tells Spring Data MongoDB how to connect to your MongoDB instance
  data:
    mongodb:
      # Connection URI for MongoDB.
      # 'localhost:27017' maps to Dockerized MongoDB container.
      # 'network_logs_db' is the database name where raw logs are dumped by Kafka Connect.
      uri: mongodb://mongoadmin:password@localhost:27017/network_logs_db

  # PostgreSQL R2DBC Connection Configuration
  # This tells Spring Data R2DBC how to connect to the PostgreSQL instance
  r2dbc:
    # R2DBC connection URL.
    # 'localhost:5432' maps to Dockerized PostgreSQL container.
    url: r2dbc:postgresql://localhost:5432/logs_db
    username: loguser
    password: logpassword

logging:
  level:
    # Log Spring Data MongoDB repository operations (e.g., find, save)
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    # Log R2DBC (PostgreSQL) queries and client activity
    io.r2dbc.postgresql.query: DEBUG
    io.r2dbc.postgresql.client: DEBUG
    org.springframework.data.r2dbc: DEBUG