spring:
  # General application name for Spring Boot Actuator, logging, etc.
  application:
    name: consumer

  # MongoDB Connection Configuration
  # This tells Spring Data MongoDB how to connect to your MongoDB instance
  data:
    mongodb:
      # Connection URI for MongoDB.
      # 'localhost:27017' maps to your Dockerized MongoDB container.
      # 'network_logs_db' is the database name where raw logs are dumped by Kafka Connect.
      uri: mongodb://mongoadmin:password@localhost:27017/network_logs_db

  # PostgreSQL R2DBC Connection Configuration
  # This tells Spring Data R2DBC how to connect to your PostgreSQL instance
  r2dbc:
    # R2DBC connection URL.
    # 'localhost:5432' maps to your Dockerized PostgreSQL container.
    # 'logs_db' is the database name you created in PostgreSQL.
    url: r2dbc:postgresql://localhost:5432/logs_db
    username: loguser # Matches POSTGRES_USER in your docker-compose-postgres.yml
    password: logpassword # Matches POSTGRES_PASSWORD in your docker-compose-postgres.yml

  # Optional: Configure logging levels for detailed debugging (useful initially)
logging:
  level:
    # Log Spring Data MongoDB repository operations (e.g., find, save)
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    # Log R2DBC (PostgreSQL) queries and client activity
    io.r2dbc.postgresql.query: DEBUG
    io.r2dbc.postgresql.client: DEBUG